pipeline {
    agent any

    stages {
        stage('Priprava') {
             steps {
                 echo 'Zacinam se psychcicky pripravovat'
             }
        }


        stage('Build') {
            steps {
                echo 'Building..'
                bat 'mvn clean package'
            }
            post {
                success {
                    echo 'Now Archiving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage ('Deploy to Staging'){
               steps {
                    build job: 'deploy-to-tostaging'
              }
        }

        stage ('Deploy to Production'){
                    steps{
                        timeout(time:30, unit:'SECONDS'){
                            input message:'Approve PRODUCTION Deployment?'
                        }

                        build job: 'deploy-to-prod'
                    }
                    post {
                        success {
                            echo 'Code deployed to Production.'
                        }

                        failure {
                            echo ' Deployment failed.'
                        }
                    }
         }
    }
}